# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Rockset < Formula
  desc "Rockset CLI"
  homepage "https://github.com/rockset/cli"
  version "0.0.23"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/rockset/cli/releases/download/v0.0.23/rockset_Darwin_x86_64.tar.gz"
      sha256 "d92c223b348cce71f0345cbe27475236a952662acfd94f23728bf81c18f901a3"

      def install
        bin.install "rockset"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/rockset/cli/releases/download/v0.0.23/rockset_Darwin_arm64.tar.gz"
      sha256 "edda1b1233defa094311625ee9712cdced12ba8a349678d9ceba9addd9abbbc9"

      def install
        bin.install "rockset"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/rockset/cli/releases/download/v0.0.23/rockset_Linux_x86_64.tar.gz"
      sha256 "9af945a824ef427a37117daeff10e498426f55bb46136e83ab3d03bb813dcb9b"

      def install
        bin.install "rockset"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/rockset/cli/releases/download/v0.0.23/rockset_Linux_arm64.tar.gz"
      sha256 "a2d4a12660bf46b90e7ad9b8904003dbf87148a0136efea96351696bd382cb53"

      def install
        bin.install "rockset"
      end
    end
  end
end
