# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Rockset < Formula
  desc "Rockset CLI"
  homepage "https://github.com/rockset/cli"
  version "0.0.25"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/rockset/cli/releases/download/v0.0.25/rockset_Darwin_x86_64.tar.gz"
      sha256 "6b777a05b439c0d1cf88eb69157a539e5cb18862074ae5699806e19885bd6b37"

      def install
        bin.install "rockset"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/rockset/cli/releases/download/v0.0.25/rockset_Darwin_arm64.tar.gz"
      sha256 "1d1d7874c87eb50aa75958b83cee940c99dda89545053a2807fd31ff7b63d252"

      def install
        bin.install "rockset"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/rockset/cli/releases/download/v0.0.25/rockset_Linux_x86_64.tar.gz"
      sha256 "b7bea793301e38e5b47caf42d7f229ae65d53959f3ff01bfa14c78e3ad67d057"

      def install
        bin.install "rockset"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/rockset/cli/releases/download/v0.0.25/rockset_Linux_arm64.tar.gz"
      sha256 "3ec9c92958614444036dd8fc9c63a143f93033800deb89cb37f4b42f5af81318"

      def install
        bin.install "rockset"
      end
    end
  end
end
